### ISSUE TITLE
Low fps  

### ISSUE THREAD

**Issue by doomtrigger** [CoreKeeperMods/CoreLib#11]
Just game a couple QoL mods installed and corelib yet the fps drops to 20 turning those mods off did not fix the fps drop

**Comment by limoka** [comment]
Please show your log, located `C:\Users\<user-name>\AppData\LocalLow\Pugstorm\Core Keeper`, send `Player.log` file from there.

**Comment by doomtrigger** [comment]
[Player.log](https://github.com/user-attachments/files/16828674/Player.log)

**Comment by limoka** [comment]
There are no mods enabled in this log. Low fps cannot be caused by CoreLib if it's not even enabled.

**Comment by limoka** [comment]
Are you sure said issue is even caused by CoreLib? Are you sure nothing else is running at the same time?

**Comment by doomtrigger** [comment]
Sorry that was after turning all the mods off ill. but found what was causing the issues CoreLib.RewiredExtension was being skipped even after it was enabled and Auto fish was causing the low fps

**Comment by limoka** [comment]
Is your issue resolved?

**Comment by doomtrigger** [comment]
yes sorry
